/**
 * Curriculum Seeder (NOVA-302)
 *
 * Creates 3 Explorer-stage learning paths with curriculum content
 * Each path has 8 lessons with 6 cards per lesson
 */

import { getPrismaClient } from './client';

interface Card {
  title: string;
  bodyText: string;
  voiceScript: string;
  type: 'story' | 'concept' | 'experiment' | 'quiz' | 'voice';
  sortOrder: number;
  content: Record<string, any>;
}

interface Lesson {
  title: string;
  description: string;
  cards: Card[];
}

interface LearningPath {
  title: string;
  description: string;
  icon: string;
  color: string;
  lessons: Lesson[];
}

const CURRICULUM: LearningPath[] = [
  {
    title: 'How Computers Think',
    description: 'Learn how computers work and think',
    icon: '💻',
    color: '#4ECDC4',
    lessons: [
      {
        title: 'What is a Computer?',
        description: 'Introduction to computers for young learners',
        cards: [
          {
            title: 'The Magic Box',
            bodyText: 'A computer is like a magical helper that lives in a box. It can remember things, count, and show us pictures!',
            voiceScript: 'A computer is like a magical helper in a box!',
            type: 'story',
            sortOrder: 1,
            content: { imagePrompt: 'A colorful computer with eyes, smiling and helpful' },
          },
          {
            title: 'What Can Computers Do?',
            bodyText: 'Computers help us play games, watch videos, draw pictures, and learn new things. They are super smart helpers!',
            voiceScript: 'Computers help us play, watch, draw, and learn.',
            type: 'concept',
            sortOrder: 2,
            content: { examples: ['Play games', 'Watch videos', 'Draw pictures', 'Learn things'] },
          },
          {
            title: 'Your iPad is a Computer',
            bodyText: 'The iPad you are using right now is a computer! It has a screen you can touch and a brain inside that makes it work.',
            voiceScript: 'Your iPad is a computer too!',
            type: 'concept',
            sortOrder: 3,
            content: { imagePrompt: 'A happy iPad character with a glowing brain' },
          },
          {
            title: 'Find the Computer',
            bodyText: 'Look around your home. Can you find other computers? Computers can be big or small. They can look different but they all help us!',
            voiceScript: 'Can you find a computer in your home?',
            type: 'experiment',
            sortOrder: 4,
            content: {
              experimentSetup: 'Look around your home and find things with screens or buttons.',
              experimentItems: ['Laptop', 'Phone', 'Smart watch'],
              experimentTargets: ['Things that are computers', 'Things that are not computers'],
            },
          },
          {
            title: 'What is Your Favorite Computer Activity?',
            bodyText: 'What do you like to do on computers? Playing? Drawing? Watching? Tell us your favorite!',
            voiceScript: 'Tell me what you like to do on computers!',
            type: 'quiz',
            sortOrder: 5,
            content: {
              quizQuestion: 'What is your favorite computer activity?',
              quizOptions: ['Playing games', 'Drawing pictures', 'Watching videos', 'Learning new things'],
              quizCorrectIndex: -1, // All answers are correct
              quizHint: 'There is no wrong answer! What do you love?',
            },
          },
          {
            title: 'Great Job!',
            bodyText: 'You learned about computers! You are a super smart explorer. Keep going!',
            voiceScript: 'You did great! You are a computer explorer!',
            type: 'voice',
            sortOrder: 6,
            content: { prompt: 'Say: I am a computer explorer!' },
          },
        ],
      },
      {
        title: 'Binary & Bits',
        description: 'Understanding ones and zeros',
        cards: [
          {
            title: 'On and Off',
            bodyText: 'Computers understand only two things: on and off. Like a light switch! On is like 1, off is like 0.',
            voiceScript: 'Computers like on and off, like light switches!',
            type: 'story',
            sortOrder: 1,
            content: { imagePrompt: 'Light switches flipping on and off, with happy faces' },
          },
          {
            title: 'Bits are Tiny',
            bodyText: 'A bit is the smallest piece of computer information. It can be 1 (on) or 0 (off). Many bits together make words and pictures!',
            voiceScript: 'Bits are tiny pieces that are on or off.',
            type: 'concept',
            sortOrder: 2,
            content: { imagePrompt: 'Tiny cute characters showing 1s and 0s' },
          },
          {
            title: 'Everything is 1s and 0s',
            bodyText: 'Every game, video, and picture on your computer is really just a long list of 1s and 0s! But you see fun colors and shapes.',
            voiceScript: 'Everything is really just ones and zeros!',
            type: 'concept',
            sortOrder: 3,
            content: { imagePrompt: 'Transformation from code to colorful images' },
          },
          {
            title: 'Make Your Own Code',
            bodyText: 'Let us make a simple pattern with on and off: ON, OFF, ON, ON, OFF. Can you follow the pattern?',
            voiceScript: 'Let us make a pattern with on and off!',
            type: 'experiment',
            sortOrder: 4,
            content: {
              experimentSetup: 'Tap the buttons to make a pattern of ON and OFF.',
              experimentItems: ['ON button', 'OFF button', 'YOUR turn'],
              experimentTargets: ['Make the pattern', 'Check your answer'],
            },
          },
          {
            title: 'What Else Uses On and Off?',
            bodyText: 'Many things in your home use on and off! Lights, fans, refrigerators. Everything has an on and off state.',
            voiceScript: 'What things in your home turn on and off?',
            type: 'quiz',
            sortOrder: 5,
            content: {
              quizQuestion: 'Which uses ON and OFF?',
              quizOptions: ['A light', 'A fan', 'A TV', 'All of the above'],
              quizCorrectIndex: 3,
              quizHint: 'Think about what you can turn on and off at home!',
            },
          },
          {
            title: 'You Know Binary!',
            bodyText: 'You now understand how computers think! On, off, on, off. You are becoming a code expert!',
            voiceScript: 'You understand binary now!',
            type: 'voice',
            sortOrder: 6,
            content: { prompt: 'Say: I understand ones and zeros!' },
          },
        ],
      },
      {
        title: 'How Programs Run',
        description: 'Programs are like recipes for computers',
        cards: [
          {
            title: 'Programs are Recipes',
            bodyText: 'Just like a recipe tells you how to make cookies step by step, a program tells a computer what to do step by step!',
            voiceScript: 'Programs are like recipes for computers!',
            type: 'story',
            sortOrder: 1,
            content: { imagePrompt: 'Chef computer following a recipe card' },
          },
          {
            title: 'Follow the Steps',
            bodyText: 'A computer follows a program exactly. First do this, then do that, then do this. It never skips a step!',
            voiceScript: 'Computers follow steps carefully.',
            type: 'concept',
            sortOrder: 2,
            content: { imagePrompt: 'Steps numbered 1, 2, 3 with a computer walking on them' },
          },
          {
            title: 'Step by Step',
            bodyText: 'Every time you tap a button on this iPad, a program runs. It says: first check what was tapped, then change the screen, then show it!',
            voiceScript: 'When you tap a button, a program runs!',
            type: 'concept',
            sortOrder: 3,
            content: { imagePrompt: 'A finger tapping a screen with gears turning inside' },
          },
          {
            title: 'Make Your Own Program',
            bodyText: 'You can make a simple program! Pick an action. Step 1: tap a button. Step 2: clap your hands. Step 3: say hooray!',
            voiceScript: 'Let us make a program together!',
            type: 'experiment',
            sortOrder: 4,
            content: {
              experimentSetup: 'Follow these steps: 1) Tap here, 2) Clap your hands, 3) Say hooray!',
              experimentItems: ['Step 1: Tap', 'Step 2: Clap', 'Step 3: Say hooray'],
              experimentTargets: ['Follow all steps', 'Do it in order'],
            },
          },
          {
            title: 'What Happens if Steps are Wrong?',
            bodyText: 'If a program has the wrong steps, something silly happens! Programs must be exactly right to work perfectly.',
            voiceScript: 'Programs need the right steps!',
            type: 'quiz',
            sortOrder: 5,
            content: {
              quizQuestion: 'If a program has wrong steps, what happens?',
              quizOptions: ['Something silly', 'The computer knows better', 'Nothing', 'The computer fixes it'],
              quizCorrectIndex: 0,
              quizHint: 'Think about following instructions wrong!',
            },
          },
          {
            title: 'You Know Programming!',
            bodyText: 'You understand how programs work! You are a super programmer now!',
            voiceScript: 'You understand programs!',
            type: 'voice',
            sortOrder: 6,
            content: { prompt: 'Say: I know how programs work!' },
          },
        ],
      },
      {
        title: 'Memory & Storage',
        description: 'Where computers remember things',
        cards: [
          {
            title: 'Computers Have Memory',
            bodyText: 'Computers have memory, just like you! They remember where you left off in a game, your scores, and your favorite pictures!',
            voiceScript: 'Computers remember things!',
            type: 'story',
            sortOrder: 1,
            content: { imagePrompt: 'A computer with a brain full of glowing memories' },
          },
          {
            title: 'RAM is Super Fast Memory',
            bodyText: 'RAM is like a computer\'s brain. It remembers things while the computer is on. When you turn it off, RAM forgets! But that is okay!',
            voiceScript: 'RAM is fast but forgets when you turn off.',
            type: 'concept',
            sortOrder: 2,
            content: { imagePrompt: 'RAM chips glowing and working fast' },
          },
          {
            title: 'Storage Remembers Forever',
            bodyText: 'Storage is like a computer\'s notebook. It keeps memories even when you turn off the computer! Your photos stay saved!',
            voiceScript: 'Storage remembers forever!',
            type: 'concept',
            sortOrder: 3,
            content: { imagePrompt: 'A book storing memories and photos' },
          },
          {
            title: 'How Much Memory?',
            bodyText: 'This iPad has storage for hundreds of games and thousands of photos! Let us see how much space we are using.',
            voiceScript: 'Let us check our iPad memory!',
            type: 'experiment',
            sortOrder: 4,
            content: {
              experimentSetup: 'Go to Settings and look for Storage or About. See how full your iPad is!',
              experimentItems: ['Open Settings', 'Find Storage', 'See how full it is'],
              experimentTargets: ['Storage used', 'Storage available'],
            },
          },
          {
            title: 'What Disappears vs What Stays?',
            bodyText: 'When you turn off your computer, some things go away (RAM) but your games and photos stay (Storage).',
            voiceScript: 'Some things disappear, some things stay!',
            type: 'quiz',
            sortOrder: 5,
            content: {
              quizQuestion: 'What stays when you turn off the computer?',
              quizOptions: ['Your games', 'Your photos', 'Your drawings', 'All of them'],
              quizCorrectIndex: 3,
              quizHint: 'Think about what you find when you turn the iPad back on!',
            },
          },
          {
            title: 'You Know Memory!',
            bodyText: 'You understand how computers remember! You are a memory master!',
            voiceScript: 'You understand memory!',
            type: 'voice',
            sortOrder: 6,
            content: { prompt: 'Say: I know about computer memory!' },
          },
        ],
      },
      {
        title: 'Input & Output',
        description: 'How we talk to computers and they talk to us',
        cards: [
          {
            title: 'Talking to Computers',
            bodyText: 'We use INPUT to tell computers what to do. We tap, type, talk, or move our hands. The computer listens!',
            voiceScript: 'We input information to computers!',
            type: 'story',
            sortOrder: 1,
            content: { imagePrompt: 'A child tapping and talking to a computer' },
          },
          {
            title: 'Computers Talk Back',
            bodyText: 'Computers use OUTPUT to tell us things. They show us pictures on screens, play sounds, and vibrate! The computer talks back!',
            voiceScript: 'Computers output information to us!',
            type: 'concept',
            sortOrder: 2,
            content: { imagePrompt: 'Computer screens, speakers, and vibrations communicating' },
          },
          {
            title: 'Input Examples',
            bodyText: 'When you tap a button, that is input. When you type words, that is input. When you say something to Dashy, that is input!',
            voiceScript: 'Tapping, typing, and talking are all inputs!',
            type: 'concept',
            sortOrder: 3,
            content: { imagePrompt: 'Hands tapping, fingers typing, mouth talking to a screen' },
          },
          {
            title: 'Find Input and Output',
            bodyText: 'Look at your iPad. Which parts are for INPUT (you control)? Which are for OUTPUT (it shows you)?',
            voiceScript: 'Let us find input and output!',
            type: 'experiment',
            sortOrder: 4,
            content: {
              experimentSetup: 'Touch the screen (input), watch it respond (output). Try tapping different areas!',
              experimentItems: ['Screen (input)', 'Speaker (output)', 'Buttons (input)'],
              experimentTargets: ['Things you control', 'Things that respond'],
            },
          },
          {
            title: 'What is Input?',
            bodyText: 'When you play a game and touch the screen to make a character jump, what is that?',
            voiceScript: 'What is input?',
            type: 'quiz',
            sortOrder: 5,
            content: {
              quizQuestion: 'Touching the screen is what?',
              quizOptions: ['Input', 'Output', 'Memory', 'Code'],
              quizCorrectIndex: 0,
              quizHint: 'Is it something you do to the computer?',
            },
          },
          {
            title: 'You Know Input and Output!',
            bodyText: 'You understand how we talk to computers! You are a communication expert!',
            voiceScript: 'You know input and output!',
            type: 'voice',
            sortOrder: 6,
            content: { prompt: 'Say: I understand input and output!' },
          },
        ],
      },
      {
        title: 'The Internet',
        description: 'Computers connected around the world',
        cards: [
          {
            title: 'Connected Computers',
            bodyText: 'The Internet is like a giant web that connects millions of computers all around the world! They can send messages to each other!',
            voiceScript: 'The Internet connects computers everywhere!',
            type: 'story',
            sortOrder: 1,
            content: { imagePrompt: 'Computers connected by glowing wires around a globe' },
          },
          {
            title: 'How Do Computers Talk?',
            bodyText: 'Computers send information in tiny pieces called packets. Each packet travels through the internet like a postcard, and finally arrives!',
            voiceScript: 'Packets travel through the Internet!',
            type: 'concept',
            sortOrder: 2,
            content: { imagePrompt: 'Little envelopes traveling through glowing Internet highways' },
          },
          {
            title: 'What Travels on the Internet?',
            bodyText: 'Videos, games, photos, messages, and websites all travel on the Internet! They come from computers far, far away to your iPad!',
            voiceScript: 'Videos and games travel through the Internet!',
            type: 'concept',
            sortOrder: 3,
            content: { imagePrompt: 'Videos, games, and pictures flowing from far away' },
          },
          {
            title: 'Build an Internet',
            bodyText: 'You and your friends can make a human Internet! Stand in a line and pass a ball (packet) to each other. That is like the Internet!',
            voiceScript: 'Let us make a human Internet!',
            type: 'experiment',
            sortOrder: 4,
            content: {
              experimentSetup: 'Get friends to stand in a line. Pass a ball from person to person. Each person is a computer!',
              experimentItems: ['People', 'A ball (packet)', 'A line'],
              experimentTargets: ['Pass the ball', 'Each person is connected'],
            },
          },
          {
            title: 'Where Does the Internet Live?',
            bodyText: 'The Internet is made of cables under streets, in buildings, and under oceans! Special computers called servers store all the information!',
            voiceScript: 'The Internet has cables everywhere!',
            type: 'quiz',
            sortOrder: 5,
            content: {
              quizQuestion: 'What carries Internet information?',
              quizOptions: ['Cables', 'Air', 'Water', 'Light'],
              quizCorrectIndex: 0,
              quizHint: 'Think about how the information gets to your house!',
            },
          },
          {
            title: 'You Know the Internet!',
            bodyText: 'You understand the Internet! You are connected to the whole world!',
            voiceScript: 'You know about the Internet!',
            type: 'voice',
            sortOrder: 6,
            content: { prompt: 'Say: I understand the Internet!' },
          },
        ],
      },
      {
        title: 'Search Engines',
        description: 'Finding information on the web',
        cards: [
          {
            title: 'The Information Library',
            bodyText: 'The Internet has billions and billions of pages with information. How do we find what we need? Search engines help us!',
            voiceScript: 'Search engines help us find information!',
            type: 'story',
            sortOrder: 1,
            content: { imagePrompt: 'A magical search engine with information flying everywhere' },
          },
          {
            title: 'How Search Works',
            bodyText: 'You type a word in the search box. The search engine looks through millions of pages and shows you the best matches!',
            voiceScript: 'Search engines find pages for you!',
            type: 'concept',
            sortOrder: 2,
            content: { imagePrompt: 'A search box with pages flying out of it' },
          },
          {
            title: 'Good Search Words',
            bodyText: 'When you search, pick good words. Instead of a long sentence, use short words. Search for "dinosaurs" not "tell me about dinosaurs"!',
            voiceScript: 'Use short, simple search words!',
            type: 'concept',
            sortOrder: 3,
            content: { imagePrompt: 'A comparison of good vs bad search terms' },
          },
          {
            title: 'Try a Search',
            bodyText: 'Let us use a safe search engine to find something you like! Maybe animals, or space, or your favorite hobby!',
            voiceScript: 'Let us try searching!',
            type: 'experiment',
            sortOrder: 4,
            content: {
              experimentSetup: 'Ask a grown-up to help you search for something fun. Type in a short word and see what you find!',
              experimentItems: ['Search word 1', 'Search word 2', 'Look at results'],
              experimentTargets: ['Find information', 'Read what you found'],
            },
          },
          {
            title: 'Why Does Search Matter?',
            bodyText: 'Search engines help us learn new things, find answers, and discover cool information!',
            voiceScript: 'Search engines help us learn!',
            type: 'quiz',
            sortOrder: 5,
            content: {
              quizQuestion: 'What do search engines do?',
              quizOptions: ['Help us find pages', 'Play games', 'Tell jokes', 'Make the Internet'],
              quizCorrectIndex: 0,
              quizHint: 'Think about what happens when you type a word!',
            },
          },
          {
            title: 'You Can Search!',
            bodyText: 'You now know how to search for information! You can find anything you are curious about!',
            voiceScript: 'You can search!',
            type: 'voice',
            sortOrder: 6,
            content: { prompt: 'Say: I can use a search engine!' },
          },
        ],
      },
      {
        title: 'Coding Basics',
        description: 'Learning to code is like talking to computers',
        cards: [
          {
            title: 'What is Code?',
            bodyText: 'Code is like a special language. It is how we tell computers exactly what to do. Computers understand code, but not English!',
            voiceScript: 'Code is a language for computers!',
            type: 'story',
            sortOrder: 1,
            content: { imagePrompt: 'A computer speaking a language of colorful code symbols' },
          },
          {
            title: 'Programmers Write Code',
            bodyText: 'Programmers are like computer teachers. They write code to tell computers how to work. They write millions of lines of code!',
            voiceScript: 'Programmers write instructions for computers!',
            type: 'concept',
            sortOrder: 2,
            content: { imagePrompt: 'A programmer typing code on a screen with glowing letters' },
          },
          {
            title: 'Code Makes Everything',
            bodyText: 'Every game, app, and website you use was made by programmers writing code. Code is magic that makes the Internet work!',
            voiceScript: 'Code makes games and apps!',
            type: 'concept',
            sortOrder: 3,
            content: { imagePrompt: 'Code transforming into apps and games' },
          },
          {
            title: 'Practice Simple Code',
            bodyText: 'We can practice code with blocks! Each block is like a simple instruction. Stack blocks together to make a program!',
            voiceScript: 'Let us practice code with blocks!',
            type: 'experiment',
            sortOrder: 4,
            content: {
              experimentSetup: 'Drag code blocks to make a character move. Each block does one thing.',
              experimentItems: ['Move block', 'Turn block', 'Jump block'],
              experimentTargets: ['Make a path', 'Make the character move'],
            },
          },
          {
            title: 'What is a Bug in Code?',
            bodyText: 'When code does not work right, it is called a bug. Programmers fix bugs by looking at the code and finding what is wrong!',
            voiceScript: 'Bugs are mistakes in code!',
            type: 'quiz',
            sortOrder: 5,
            content: {
              quizQuestion: 'What is a bug in code?',
              quizOptions: ['An insect', 'A mistake', 'A game', 'A computer'],
              quizCorrectIndex: 1,
              quizHint: 'It is a mistake in instructions!',
            },
          },
          {
            title: 'You Can Code!',
            bodyText: 'You are learning to code! Maybe one day you will be a programmer and make your own game!',
            voiceScript: 'You can code!',
            type: 'voice',
            sortOrder: 6,
            content: { prompt: 'Say: I can code computers!' },
          },
        ],
      },
    ],
  },
  {
    title: 'Robot Adventures',
    description: 'Explore the world of robots',
    icon: '🤖',
    color: '#FF6B6B',
    lessons: [
      {
        title: 'What is a Robot?',
        description: 'Introduction to robots',
        cards: [
          {
            title: 'Robots are Helpers',
            bodyText: 'A robot is a machine that can move and think. It can do tasks that we ask it to do. Some robots build cars, some clean floors!',
            voiceScript: 'Robots are helpful machines!',
            type: 'story',
            sortOrder: 1,
            content: { imagePrompt: 'A friendly robot helper waving and smiling' },
          },
          {
            title: 'Robots Have Parts',
            bodyText: 'Robots have sensors to see and feel, motors to move, and a computer brain to think. Together they make a robot work!',
            voiceScript: 'Robots have sensors, motors, and brains!',
            type: 'concept',
            sortOrder: 2,
            content: { imagePrompt: 'A robot with highlighted sensors, motors, and brain' },
          },
          {
            title: 'Robots Are Everywhere',
            bodyText: 'Robots help us in factories, hospitals, and even our homes! They can do dangerous, boring, or hard jobs so people stay safe!',
            voiceScript: 'Robots help us every day!',
            type: 'concept',
            sortOrder: 3,
            content: { imagePrompt: 'Different robots in different places' },
          },
          {
            title: 'Design Your Robot',
            bodyText: 'What would your robot do? Would it clean? Cook? Play? Draw a picture of your dream robot!',
            voiceScript: 'What would your robot do?',
            type: 'experiment',
            sortOrder: 4,
            content: {
              experimentSetup: 'Draw or describe your own robot. What job does it do? What does it look like?',
              experimentItems: ['Draw', 'Describe', 'Imagine'],
              experimentTargets: ['Design robot', 'Name your robot'],
            },
          },
          {
            title: 'What Does a Robot Need?',
            bodyText: 'A robot needs power to run, instructions to follow, and sensors to understand the world!',
            voiceScript: 'Robots need power and instructions!',
            type: 'quiz',
            sortOrder: 5,
            content: {
              quizQuestion: 'What does a robot need to work?',
              quizOptions: ['Power and instructions', 'Food', 'Water', 'Sleep'],
              quizCorrectIndex: 0,
              quizHint: 'Think about what computers need!',
            },
          },
          {
            title: 'You Know Robots!',
            bodyText: 'You understand what robots are! You are a robot expert!',
            voiceScript: 'You know about robots!',
            type: 'voice',
            sortOrder: 6,
            content: { prompt: 'Say: I understand robots!' },
          },
        ],
      },
      {
        title: 'Sensors & Senses',
        description: 'How robots sense the world',
        cards: [
          {
            title: 'Robots Have Senses',
            bodyText: 'Like you have eyes to see and ears to hear, robots have sensors! Sensors help robots understand the world around them.',
            voiceScript: 'Robots have sensors!',
            type: 'story',
            sortOrder: 1,
            content: { imagePrompt: 'A robot with big sensor eyes and antenna ears' },
          },
          {
            title: 'Camera Sensors',
            bodyText: 'Camera sensors are robot eyes. They see colors, shapes, and movement. Your iPad camera is a sensor!',
            voiceScript: 'Camera sensors are robot eyes!',
            type: 'concept',
            sortOrder: 2,
            content: { imagePrompt: 'A robot eye and an iPad camera' },
          },
          {
            title: 'Touch Sensors',
            bodyText: 'Touch sensors help robots feel things. They know when something is hot, cold, soft, or hard. Your fingers are touch sensors!',
            voiceScript: 'Touch sensors help robots feel!',
            type: 'concept',
            sortOrder: 3,
            content: { imagePrompt: 'Robot fingers touching different materials' },
          },
          {
            title: 'Discover Your Sensors',
            bodyText: 'Your body has amazing sensors! Your eyes see, ears hear, nose smells, tongue tastes, and skin feels. You are full of sensors!',
            voiceScript: 'Your body has sensors!',
            type: 'experiment',
            sortOrder: 4,
            content: {
              experimentSetup: 'Try using each sensor. Look at something, listen for sounds, smell something safe, taste something yummy, touch something!',
              experimentItems: ['Eyes (see)', 'Ears (hear)', 'Nose (smell)', 'Tongue (taste)', 'Skin (touch)'],
              experimentTargets: ['Use each sensor', 'Say what you sense'],
            },
          },
          {
            title: 'What Sense Does a Robot Use Most?',
            bodyText: 'Many robots use camera sensors first because they can see far away. Then they use other sensors to check details!',
            voiceScript: 'Robots see with cameras!',
            type: 'quiz',
            sortOrder: 5,
            content: {
              quizQuestion: 'What sensor is like a robot eye?',
              quizOptions: ['Camera', 'Microphone', 'Thermometer', 'Motor'],
              quizCorrectIndex: 0,
              quizHint: 'Think about what robots see with!',
            },
          },
          {
            title: 'You Have Senses!',
            bodyText: 'You have many sensors! Your senses help you learn about the world, just like a robot!',
            voiceScript: 'You have sensors too!',
            type: 'voice',
            sortOrder: 6,
            content: { prompt: 'Say: My senses help me learn!' },
          },
        ],
      },
      {
        title: 'Motors & Movement',
        description: 'How robots move',
        cards: [
          {
            title: 'Motors Make Robots Move',
            bodyText: 'Motors are like robot muscles! They spin and push to make robots move. Wheels, arms, and legs all use motors!',
            voiceScript: 'Motors make robots move!',
            type: 'story',
            sortOrder: 1,
            content: { imagePrompt: 'A robot with spinning motors and moving parts' },
          },
          {
            title: 'Different Movements',
            bodyText: 'Motors can make robots roll, walk, fly, or spin! Different motors do different jobs. Some are strong, some are fast!',
            voiceScript: 'Motors can do many movements!',
            type: 'concept',
            sortOrder: 2,
            content: { imagePrompt: 'Different robots with different movements' },
          },
          {
            title: 'Your Muscles are Motors',
            bodyText: 'Your muscles are like biological motors! They help you run, jump, dance, and move. You are like a human robot!',
            voiceScript: 'Your muscles are like motors!',
            type: 'concept',
            sortOrder: 3,
            content: { imagePrompt: 'A child and a robot moving together' },
          },
          {
            title: 'Move Like a Robot',
            bodyText: 'Can you move like different robots? Walk like a robot with stiff legs. Roll like a wheel. Spin like a spinning top!',
            voiceScript: 'Let us move like robots!',
            type: 'experiment',
            sortOrder: 4,
            content: {
              experimentSetup: 'Move your body like different robots. Be stiff like a walking robot. Roll. Spin. Jump!',
              experimentItems: ['Walk stiffly', 'Roll', 'Spin', 'Jump'],
              experimentTargets: ['Do each movement', 'Be a robot!'],
            },
          },
          {
            title: 'Why Do Robots Need Motors?',
            bodyText: 'Without motors, robots cannot move! Motors turn electricity into motion. That is robot magic!',
            voiceScript: 'Robots need motors to move!',
            type: 'quiz',
            sortOrder: 5,
            content: {
              quizQuestion: 'What makes a robot move?',
              quizOptions: ['Motors', 'Wheels', 'Electricity', 'Wind'],
              quizCorrectIndex: 0,
              quizHint: 'It is the robot muscle!',
            },
          },
          {
            title: 'You Understand Movement!',
            bodyText: 'You now know how robots move! You are a movement master!',
            voiceScript: 'You understand robot movement!',
            type: 'voice',
            sortOrder: 6,
            content: { prompt: 'Say: I know how robots move!' },
          },
        ],
      },
      {
        title: 'Robot Brains',
        description: 'The computer inside robots',
        cards: [
          {
            title: 'Robots Have Brains',
            bodyText: 'Deep inside every robot is a computer that thinks! The robot brain gets information from sensors and decides what to do!',
            voiceScript: 'Robots have thinking brains!',
            type: 'story',
            sortOrder: 1,
            content: { imagePrompt: 'A glowing brain inside a robot head' },
          },
          {
            title: 'The Robot Brain Thinks Fast',
            bodyText: 'A robot brain can think millions of times faster than we can! It sees, thinks, and makes decisions in just seconds!',
            voiceScript: 'Robot brains think very fast!',
            type: 'concept',
            sortOrder: 2,
            content: { imagePrompt: 'A fast-thinking computer with lightning bolts' },
          },
          {
            title: 'Programming the Brain',
            bodyText: 'Programmers write code to tell the robot brain what to do. The code teaches the robot how to see, think, and move!',
            voiceScript: 'Programmers teach robot brains!',
            type: 'concept',
            sortOrder: 3,
            content: { imagePrompt: 'Code flowing into a robot brain' },
          },
          {
            title: 'Make a Decision Chain',
            bodyText: 'Help us write a decision chain for a robot. If it sees red, it stops. If it sees green, it goes. What else?',
            voiceScript: 'Let us teach a robot!',
            type: 'experiment',
            sortOrder: 4,
            content: {
              experimentSetup: 'Write if-then rules: If see RED, then STOP. If see GREEN, then GO. Add your own rules!',
              experimentItems: ['If RED, then...', 'If GREEN, then...', 'If BLUE, then...'],
              experimentTargets: ['Make rules', 'Create decision chain'],
            },
          },
          {
            title: 'What Does a Robot Brain Need?',
            bodyText: 'A robot brain needs power, information from sensors, and code that tells it what to do!',
            voiceScript: 'Robot brains need code!',
            type: 'quiz',
            sortOrder: 5,
            content: {
              quizQuestion: 'What tells a robot brain what to do?',
              quizOptions: ['Code', 'Wheels', 'Food', 'Friends'],
              quizCorrectIndex: 0,
              quizHint: 'Think about programming!',
            },
          },
          {
            title: 'You Can Program!',
            bodyText: 'You understand robot brains! You could be a robot programmer!',
            voiceScript: 'You understand robot brains!',
            type: 'voice',
            sortOrder: 6,
            content: { prompt: 'Say: I can program robots!' },
          },
        ],
      },
      {
        title: 'Robots at Home',
        description: 'Robots that help families',
        cards: [
          {
            title: 'Robots Help at Home',
            bodyText: 'Many robots live in homes! Vacuum robots clean floors. Smart speakers play music. Robot toys play with us!',
            voiceScript: 'Robots help at home!',
            type: 'story',
            sortOrder: 1,
            content: { imagePrompt: 'Friendly robots in a happy home' },
          },
          {
            title: 'Robot Vacuum',
            bodyText: 'A robot vacuum has sensors to see the floor and map your home. It cleans while you play! Some even go back to charging!',
            voiceScript: 'Robot vacuums clean homes!',
            type: 'concept',
            sortOrder: 2,
            content: { imagePrompt: 'A cute robot vacuum rolling around cleaning' },
          },
          {
            title: 'Smart Helpers',
            bodyText: 'Smart speakers listen to your voice and help you. They play music, answer questions, and control lights!',
            voiceScript: 'Smart speakers are helpful!',
            type: 'concept',
            sortOrder: 3,
            content: { imagePrompt: 'A smart speaker listening and helping' },
          },
          {
            title: 'Find Home Robots',
            bodyText: 'Look around your home. Can you find any robots? Smart speakers? Cameras? Motion detectors? List all the robots you find!',
            voiceScript: 'Let us find robots at home!',
            type: 'experiment',
            sortOrder: 4,
            content: {
              experimentSetup: 'Walk around your home and look for robots and smart devices. Use your checklist!',
              experimentItems: ['Smart speaker', 'Robot toy', 'Smart light', 'Camera'],
              experimentTargets: ['Find them', 'Count them'],
            },
          },
          {
            title: 'What Home Robot Do You Want?',
            bodyText: 'Imagine a robot that helps your family. What would it do? Clean? Organize? Play with you?',
            voiceScript: 'What home robot would you want?',
            type: 'quiz',
            sortOrder: 5,
            content: {
              quizQuestion: 'What would a home robot do?',
              quizOptions: ['Clean the house', 'Play games', 'Help with chores', 'All of them'],
              quizCorrectIndex: 3,
              quizHint: 'Think about what you need help with!',
            },
          },
          {
            title: 'You Know Home Robots!',
            bodyText: 'You understand how robots help families! Your future home will have many robot helpers!',
            voiceScript: 'You know about home robots!',
            type: 'voice',
            sortOrder: 6,
            content: { prompt: 'Say: Robots help my home!' },
          },
        ],
      },
      {
        title: 'Robots in Space',
        description: 'Robots exploring the universe',
        cards: [
          {
            title: 'Space Robots',
            bodyText: 'Robots explore space where people cannot go! They drive on Mars, repair satellites, and send pictures back to Earth!',
            voiceScript: 'Robots explore space!',
            type: 'story',
            sortOrder: 1,
            content: { imagePrompt: 'A robot driving on Mars with Earth in the sky' },
          },
          {
            title: 'Mars Rovers',
            bodyText: 'Mars Rovers are robot cars on Mars. They have wheels, cameras, and tools. Scientists drive them from Earth to explore!',
            voiceScript: 'Mars Rovers are robot cars!',
            type: 'concept',
            sortOrder: 2,
            content: { imagePrompt: 'A Mars Rover on a red desert landscape' },
          },
          {
            title: 'Robot Challenges',
            bodyText: 'Space robots are super tough! They work in extreme heat and cold. They can still work even if one part breaks!',
            voiceScript: 'Space robots are super tough!',
            type: 'concept',
            sortOrder: 3,
            content: { imagePrompt: 'A tough robot withstanding storms and extremes' },
          },
          {
            title: 'Design a Space Robot',
            bodyText: 'Design a robot for Mars or another planet. What special powers would it need? What would it be made of?',
            voiceScript: 'Let us design a space robot!',
            type: 'experiment',
            sortOrder: 4,
            content: {
              experimentSetup: 'Draw a space robot. Give it special powers for extreme environments!',
              experimentItems: ['Strong wheels', 'Heat shields', 'Science tools', 'Solar panels'],
              experimentTargets: ['Design robot', 'Name it'],
            },
          },
          {
            title: 'How Do Scientists Control Space Robots?',
            bodyText: 'Scientists send commands through radio signals! It takes minutes for the signal to reach Mars, so robots must be smart!',
            voiceScript: 'Scientists control space robots!',
            type: 'quiz',
            sortOrder: 5,
            content: {
              quizQuestion: 'How do scientists control Mars robots?',
              quizOptions: ['Radio signals', 'Magic', 'Remote control', 'A robot driver'],
              quizCorrectIndex: 0,
              quizHint: 'It is like a long-distance signal!',
            },
          },
          {
            title: 'You Know Space Robots!',
            bodyText: 'You understand space exploration! Maybe one day you will build robots for Mars!',
            voiceScript: 'You know about space robots!',
            type: 'voice',
            sortOrder: 6,
            content: { prompt: 'Say: I understand space robots!' },
          },
        ],
      },
      {
        title: 'Building a Robot',
        description: 'How to make a robot',
        cards: [
          {
            title: 'Building is Fun',
            bodyText: 'You can build robots! Start with basic parts: a motor, wheels, and sensors. Put them together and add a brain!',
            voiceScript: 'You can build robots!',
            type: 'story',
            sortOrder: 1,
            content: { imagePrompt: 'A child building a robot from colorful parts' },
          },
          {
            title: 'Robot Building Kits',
            bodyText: 'Robot building kits have all the parts you need! LEGO, Arduino, and other kits help kids build their first robots!',
            voiceScript: 'Robot kits help you build!',
            type: 'concept',
            sortOrder: 2,
            content: { imagePrompt: 'A collection of robot building parts and kits' },
          },
          {
            title: 'Building Steps',
            bodyText: 'First, you assemble the body and parts. Second, you program the brain. Third, you test it! Does it work? If not, fix it!',
            voiceScript: 'Building has steps!',
            type: 'concept',
            sortOrder: 3,
            content: { imagePrompt: 'Building steps: assemble, program, test' },
          },
          {
            title: 'Plan a Robot Project',
            bodyText: 'What robot would you build? A dancing robot? A drawing robot? A moving robot? Plan it out step by step!',
            voiceScript: 'Let us plan your robot!',
            type: 'experiment',
            sortOrder: 4,
            content: {
              experimentSetup: 'Draw your robot. List the parts you need. Write what it should do!',
              experimentItems: ['Design', 'Parts list', 'Function'],
              experimentTargets: ['Complete plan', 'Get ready to build'],
            },
          },
          {
            title: 'What is the Hardest Part?',
            bodyText: 'Building the robot is fun, but programming the brain is tricky! You have to think like a computer!',
            voiceScript: 'Programming is the hardest part!',
            type: 'quiz',
            sortOrder: 5,
            content: {
              quizQuestion: 'What is hard about building robots?',
              quizOptions: ['Programming the brain', 'Assembling parts', 'Getting materials', 'Testing'],
              quizCorrectIndex: 0,
              quizHint: 'Think about what takes thinking!',
            },
          },
          {
            title: 'You Can Build!',
            bodyText: 'You now know how to build robots! Maybe you will build the next great robot!',
            voiceScript: 'You can build robots!',
            type: 'voice',
            sortOrder: 6,
            content: { prompt: 'Say: I can build robots!' },
          },
        ],
      },
      {
        title: 'Future Robots',
        description: 'Amazing robots of tomorrow',
        cards: [
          {
            title: 'The Future is Amazing',
            bodyText: 'In the future, robots will be smarter and more helpful! Maybe robots will be best friends, doctors, or teachers!',
            voiceScript: 'The future has amazing robots!',
            type: 'story',
            sortOrder: 1,
            content: { imagePrompt: 'A futuristic city filled with helpful robots' },
          },
          {
            title: 'AI Robots',
            bodyText: 'Artificial Intelligence robots can learn and make decisions! They get smarter as they learn more. Dashy is an AI!',
            voiceScript: 'AI robots learn and grow!',
            type: 'concept',
            sortOrder: 2,
            content: { imagePrompt: 'A robot with a glowing brain getting smarter' },
          },
          {
            title: 'Robots Help Humans',
            bodyText: 'Future robots will help doctors perform surgery, help elderly people live at home, and teach children all over the world!',
            voiceScript: 'Robots help humans!',
            type: 'concept',
            sortOrder: 3,
            content: { imagePrompt: 'Robots helping in hospitals and schools' },
          },
          {
            title: 'Dream About Future Robots',
            bodyText: 'What robot do you dream of? A robot doctor? A robot friend? A robot teacher? Describe your dream robot!',
            voiceScript: 'Tell us about your dream robot!',
            type: 'experiment',
            sortOrder: 4,
            content: {
              experimentSetup: 'Close your eyes and imagine a future robot. What does it look like? What can it do?',
              experimentItems: ['Imagine', 'Draw', 'Describe'],
              experimentTargets: ['Create robot', 'Share your dream'],
            },
          },
          {
            title: 'Will Robots Be Friends?',
            bodyText: 'In the future, robots might be friends! They could understand your feelings, play with you, and help you learn!',
            voiceScript: 'Robots might be friends!',
            type: 'quiz',
            sortOrder: 5,
            content: {
              quizQuestion: 'What could future robots do?',
              quizOptions: ['Be friends', 'Understand feelings', 'Help us learn', 'All of the above'],
              quizCorrectIndex: 3,
              quizHint: 'Think about the smartest robots!',
            },
          },
          {
            title: 'You Know the Future!',
            bodyText: 'You understand robots and their future! Maybe YOU will invent the robot of the future!',
            voiceScript: 'You understand the future!',
            type: 'voice',
            sortOrder: 6,
            content: { prompt: 'Say: I can invent future robots!' },
          },
        ],
      },
    ],
  },
  {
    title: 'AI Explorers',
    description: 'Discover the world of artificial intelligence',
    icon: '🧠',
    color: '#95E1D3',
    lessons: [
      {
        title: 'What is AI?',
        description: 'Introduction to artificial intelligence',
        cards: [
          {
            title: 'AI is Smart Technology',
            bodyText: 'Artificial Intelligence (AI) means a computer that can think and learn. It is not real thinking like you, but it seems smart!',
            voiceScript: 'AI is artificial intelligence!',
            type: 'story',
            sortOrder: 1,
            content: { imagePrompt: 'A glowing AI brain with lightbulbs of ideas' },
          },
          {
            title: 'AI Learns from Examples',
            bodyText: 'AI learns by seeing many examples. Show it 100 cat photos and it learns what cats look like. Then it can find cats in new photos!',
            voiceScript: 'AI learns from examples!',
            type: 'concept',
            sortOrder: 2,
            content: { imagePrompt: 'An AI learning from cat photos' },
          },
          {
            title: 'AI is Everywhere',
            bodyText: 'AI recommends YouTube videos, translates languages, helps doctors find diseases, and powers self-driving cars!',
            voiceScript: 'AI is everywhere!',
            type: 'concept',
            sortOrder: 3,
            content: { imagePrompt: 'Different AI applications in daily life' },
          },
          {
            title: 'Find the AI',
            bodyText: 'Look at your apps and devices. Does your phone suggest words when you type? That is AI! Does it recommend videos? That is AI too!',
            voiceScript: 'Let us find AI!',
            type: 'experiment',
            sortOrder: 4,
            content: {
              experimentSetup: 'Look for AI in your apps. Is something giving you recommendations? Predicting? That might be AI!',
              experimentItems: ['Search suggestions', 'Video recommendations', 'Smart predictions'],
              experimentTargets: ['Find AI examples', 'See how smart it is'],
            },
          },
          {
            title: 'Is AI Magic?',
            bodyText: 'AI seems magical, but it is not! It is math and patterns. Millions of math calculations working together look like magic!',
            voiceScript: 'AI is math, not magic!',
            type: 'quiz',
            sortOrder: 5,
            content: {
              quizQuestion: 'What is AI really made of?',
              quizOptions: ['Magic', 'Math and code', 'Electricity', 'Learning'],
              quizCorrectIndex: 1,
              quizHint: 'Think about computers!',
            },
          },
          {
            title: 'You Know AI!',
            bodyText: 'You understand artificial intelligence! You are an AI expert!',
            voiceScript: 'You know about AI!',
            type: 'voice',
            sortOrder: 6,
            content: { prompt: 'Say: I understand AI!' },
          },
        ],
      },
      {
        title: 'How AI Learns',
        description: 'Machine learning explained',
        cards: [
          {
            title: 'Learning is Practice',
            bodyText: 'You learn by practicing. AI learns the same way! Show it many examples and it gets better and better at finding patterns!',
            voiceScript: 'AI learns like you do!',
            type: 'story',
            sortOrder: 1,
            content: { imagePrompt: 'An AI practicing and improving skills' },
          },
          {
            title: 'Training Data',
            bodyText: 'AI needs tons of examples to learn. It might learn from a million dog photos to understand what dogs look like!',
            voiceScript: 'AI needs lots of training!',
            type: 'concept',
            sortOrder: 2,
            content: { imagePrompt: 'Mountains of dog photos feeding into an AI brain' },
          },
          {
            title: 'Patterns and Predictions',
            bodyText: 'AI looks for patterns in data. If it sees that cats have pointy ears, it learns that pattern. Then it can spot cats!',
            voiceScript: 'AI finds patterns!',
            type: 'concept',
            sortOrder: 3,
            content: { imagePrompt: 'Patterns being recognized and highlighted' },
          },
          {
            title: 'Teach the AI',
            bodyText: 'We can teach AI by showing it examples! Show it different shapes and colors. After seeing many, it learns!',
            voiceScript: 'Let us teach the AI!',
            type: 'experiment',
            sortOrder: 4,
            content: {
              experimentSetup: 'Look at examples and guess what the AI is learning. Red vs blue? Big vs small? What is the pattern?',
              experimentItems: ['Red items', 'Blue items', 'Guess the pattern'],
              experimentTargets: ['Identify pattern', 'Teach like AI'],
            },
          },
          {
            title: 'How Long Does Learning Take?',
            bodyText: 'Training AI can take hours or days! Powerful computers show the AI millions of examples and it gets smarter!',
            voiceScript: 'AI training takes time!',
            type: 'quiz',
            sortOrder: 5,
            content: {
              quizQuestion: 'How does AI learn?',
              quizOptions: ['From examples', 'From mistakes', 'From patterns', 'All of the above'],
              quizCorrectIndex: 3,
              quizHint: 'Think about learning in school!',
            },
          },
          {
            title: 'You Can Train AI!',
            bodyText: 'You now understand machine learning! You could help train AI systems!',
            voiceScript: 'You can train AI!',
            type: 'voice',
            sortOrder: 6,
            content: { prompt: 'Say: I can teach AI!' },
          },
        ],
      },
      {
        title: 'Talking to AI',
        description: 'Conversation with artificial intelligence',
        cards: [
          {
            title: 'AI Can Talk',
            bodyText: 'Some AI can understand your words and talk back! Like Dashy! You ask questions and AI tries to answer them!',
            voiceScript: 'AI can talk to you!',
            type: 'story',
            sortOrder: 1,
            content: { imagePrompt: 'A child chatting with a friendly AI character' },
          },
          {
            title: 'AI Understands Language',
            bodyText: 'AI learns human languages by reading millions of sentences! It understands grammar, meanings, and even jokes!',
            voiceScript: 'AI understands language!',
            type: 'concept',
            sortOrder: 2,
            content: { imagePrompt: 'Words and languages flowing into an AI brain' },
          },
          {
            title: 'Ask the Right Questions',
            bodyText: 'To get good answers from AI, ask clear questions. "How do butterflies work?" is better than "butterflies?"',
            voiceScript: 'Ask clear questions!',
            type: 'concept',
            sortOrder: 3,
            content: { imagePrompt: 'Good vs bad questions to an AI' },
          },
          {
            title: 'Have a Conversation',
            bodyText: 'Talk to Dashy! Ask about animals, space, science, or anything you are curious about. Dashy tries to answer!',
            voiceScript: 'Let us talk to AI!',
            type: 'experiment',
            sortOrder: 4,
            content: {
              experimentSetup: 'Ask Dashy questions. See how it responds. Does it understand? Can you learn from it?',
              experimentItems: ['Ask question 1', 'Ask question 2', 'Ask question 3'],
              experimentTargets: ['Get answers', 'Learn something'],
            },
          },
          {
            title: 'Can AI Really Understand?',
            bodyText: 'AI does not understand the same way you do. It finds patterns in words, but it does not feel emotions!',
            voiceScript: 'AI is different from humans!',
            type: 'quiz',
            sortOrder: 5,
            content: {
              quizQuestion: 'Does AI understand like humans?',
              quizOptions: ['Exactly the same', 'Not the same', 'Better than humans', 'AI never understands'],
              quizCorrectIndex: 1,
              quizHint: 'Think about feelings!',
            },
          },
          {
            title: 'You Can Talk to AI!',
            bodyText: 'You can have smart conversations with AI! Keep asking questions and learning!',
            voiceScript: 'You can talk to AI!',
            type: 'voice',
            sortOrder: 6,
            content: { prompt: 'Say: I can talk to AI!' },
          },
        ],
      },
      {
        title: 'AI & Pictures',
        description: 'AI that creates and understands images',
        cards: [
          {
            title: 'AI Can Make Pictures',
            bodyText: 'AI can create pictures from words! Tell it "a purple elephant dancing" and it will try to draw it!',
            voiceScript: 'AI can make pictures!',
            type: 'story',
            sortOrder: 1,
            content: { imagePrompt: 'An AI creating colorful imaginative images' },
          },
          {
            title: 'AI Understands Pictures',
            bodyText: 'AI can look at a photo and tell you what is in it! It can recognize faces, animals, objects, and scenes!',
            voiceScript: 'AI recognizes images!',
            type: 'concept',
            sortOrder: 2,
            content: { imagePrompt: 'An AI analyzing and understanding photos' },
          },
          {
            title: 'Image Recognition',
            bodyText: 'AI learns to recognize things by seeing millions of examples. Show it 1000 dog photos and it learns "that is a dog"!',
            voiceScript: 'AI recognizes patterns in pictures!',
            type: 'concept',
            sortOrder: 3,
            content: { imagePrompt: 'AI learning to recognize dogs from photos' },
          },
          {
            title: 'Describe Your Picture',
            bodyText: 'Show AI a picture from your device. Can it tell you what is in it? Can it find specific objects? Try it!',
            voiceScript: 'Let us test AI vision!',
            type: 'experiment',
            sortOrder: 4,
            content: {
              experimentSetup: 'Show Nova a picture. Ask it to describe what it sees. Is it right? What did it notice?',
              experimentItems: ['Pick a photo', 'Ask for description', 'Check if correct'],
              experimentTargets: ['Test AI vision', 'See what it notices'],
            },
          },
          {
            title: 'Can AI Make Better Pictures Than Humans?',
            bodyText: 'AI can create pictures fast, but human artists can create with feeling and creativity! Both are special!',
            voiceScript: 'AI and humans both create!',
            type: 'quiz',
            sortOrder: 5,
            content: {
              quizQuestion: 'How is AI art different from human art?',
              quizOptions: ['AI is faster', 'Humans add feelings', 'Both can be beautiful', 'All of the above'],
              quizCorrectIndex: 3,
              quizHint: 'Think about what makes art special!',
            },
          },
          {
            title: 'You Can Use AI Art!',
            bodyText: 'You can use AI to help you create pictures and understand images! You are a creative AI user!',
            voiceScript: 'You can use AI for art!',
            type: 'voice',
            sortOrder: 6,
            content: { prompt: 'Say: I can use AI for pictures!' },
          },
        ],
      },
      {
        title: 'AI & Games',
        description: 'AI in entertainment and play',
        cards: [
          {
            title: 'AI Plays Games',
            bodyText: 'AI can play chess, checkers, video games, and even beat champions! AI players learn strategies by playing millions of times!',
            voiceScript: 'AI can play games!',
            type: 'story',
            sortOrder: 1,
            content: { imagePrompt: 'An AI playing various games skillfully' },
          },
          {
            title: 'Game AI Learns Strategy',
            bodyText: 'Video game AI learns to chase you, hide, jump, and fight! The AI gets better every time it plays!',
            voiceScript: 'Game AI learns!',
            type: 'concept',
            sortOrder: 2,
            content: { imagePrompt: 'A video game AI opponent learning and improving' },
          },
          {
            title: 'AI Opponents',
            bodyText: 'When you play against an AI opponent, it is trying to beat you! The AI reads your moves and predicts what you will do!',
            voiceScript: 'AI opponents predict your moves!',
            type: 'concept',
            sortOrder: 3,
            content: { imagePrompt: 'A player versus AI opponent with thought processes shown' },
          },
          {
            title: 'Can You Beat the AI?',
            bodyText: 'Try playing against an AI opponent! Can you win? Can you fool it? Can you find a pattern in how it plays?',
            voiceScript: 'Let us play against AI!',
            type: 'experiment',
            sortOrder: 4,
            content: {
              experimentSetup: 'Play a game against AI. Try different strategies. What does the AI do? Can you beat it?',
              experimentItems: ['Try strategy 1', 'Try strategy 2', 'Try to win'],
              experimentTargets: ['Play the game', 'Observe AI patterns'],
            },
          },
          {
            title: 'Who Wins: Human or AI?',
            bodyText: 'In complex games like chess, AI usually wins. But humans can be creative and surprise AI! Both are smart in different ways!',
            voiceScript: 'Humans and AI are both smart!',
            type: 'quiz',
            sortOrder: 5,
            content: {
              quizQuestion: 'Who usually wins at complex games?',
              quizOptions: ['AI', 'Humans', 'It depends', 'They tie'],
              quizCorrectIndex: 0,
              quizHint: 'Think about chess champions!',
            },
          },
          {
            title: 'You Can Play with AI!',
            bodyText: 'You can play games against AI and learn! Games are a fun way to see AI in action!',
            voiceScript: 'You can play with AI!',
            type: 'voice',
            sortOrder: 6,
            content: { prompt: 'Say: I can play with AI!' },
          },
        ],
      },
      {
        title: 'AI Helpers',
        description: 'How AI helps people in daily life',
        cards: [
          {
            title: 'AI Helps Everywhere',
            bodyText: 'AI helps doctors find diseases, teachers understand students, and scientists discover new medicines! AI is helpful!',
            voiceScript: 'AI helps people!',
            type: 'story',
            sortOrder: 1,
            content: { imagePrompt: 'AI helping in hospitals, schools, and labs' },
          },
          {
            title: 'AI Doctors',
            bodyText: 'AI can look at X-rays and help doctors find broken bones or diseases! AI and doctors work together as a team!',
            voiceScript: 'AI helps doctors!',
            type: 'concept',
            sortOrder: 2,
            content: { imagePrompt: 'An AI analyzing medical scans alongside a doctor' },
          },
          {
            title: 'AI Teachers',
            bodyText: 'AI can tutor you and adapt lessons to how you learn! Like Nova and Dashy! They learn your speed and help you succeed!',
            voiceScript: 'AI can teach!',
            type: 'concept',
            sortOrder: 3,
            content: { imagePrompt: 'An AI tutor teaching a happy student' },
          },
          {
            title: 'How Do You Want AI to Help?',
            bodyText: 'Imagine your own AI helper! Would it help you with homework? Chores? Finding cool things? Describe your helper!',
            voiceScript: 'Imagine your AI helper!',
            type: 'experiment',
            sortOrder: 4,
            content: {
              experimentSetup: 'Design an AI that helps you. What would it do? How would it help? Draw or describe it!',
              experimentItems: ['Design helper', 'Describe tasks', 'Name it'],
              experimentTargets: ['Create AI concept', 'Explain how it helps'],
            },
          },
          {
            title: 'Can AI Help with Everything?',
            bodyText: 'AI is great at many things, but not everything! AI cannot replace human kindness, creativity, or friendship!',
            voiceScript: 'AI helps but cannot do everything!',
            type: 'quiz',
            sortOrder: 5,
            content: {
              quizQuestion: 'What can AI NOT do well?',
              quizOptions: ['Show kindness', 'Solve problems', 'Recognize patterns', 'Play games'],
              quizCorrectIndex: 0,
              quizHint: 'Think about feelings!',
            },
          },
          {
            title: 'You Can Use AI Help!',
            bodyText: 'You can use AI to help you learn, create, and explore! AI is your partner in learning!',
            voiceScript: 'AI can help you!',
            type: 'voice',
            sortOrder: 6,
            content: { prompt: 'Say: AI helps me learn!' },
          },
        ],
      },
      {
        title: 'AI Safety',
        description: 'Using AI safely and responsibly',
        cards: [
          {
            title: 'AI Can Make Mistakes',
            bodyText: 'AI sometimes makes mistakes! It might recognize a cat as a dog or give wrong information. We must check AI answers!',
            voiceScript: 'AI is not perfect!',
            type: 'story',
            sortOrder: 1,
            content: { imagePrompt: 'An AI making a funny or harmless mistake' },
          },
          {
            title: 'Be Smart with AI',
            bodyText: 'Do not believe everything AI says. Always check information with adults or trusted sources. AI is a helper, not always right!',
            voiceScript: 'Check AI answers!',
            type: 'concept',
            sortOrder: 2,
            content: { imagePrompt: 'A child verifying AI information with trusted sources' },
          },
          {
            title: 'Private Information',
            bodyText: 'Never share personal information with AI like your address, phone number, or passwords! Keep private things private!',
            voiceScript: 'Keep information private!',
            type: 'concept',
            sortOrder: 3,
            content: { imagePrompt: 'Protected and locked information staying safe' },
          },
          {
            title: 'Safety Check',
            bodyText: 'Think before you share with AI. Is it safe? Is it private? Do you need a grown-up to help? Ask these questions!',
            voiceScript: 'Think before sharing!',
            type: 'experiment',
            sortOrder: 4,
            content: {
              experimentSetup: 'Read scenarios. Decide if they are safe to share with AI. Ask grown-ups for help!',
              experimentItems: ['My favorite hobby', 'My home address', 'My birthday'],
              experimentTargets: ['Identify safe items', 'Protect privacy'],
            },
          },
          {
            title: 'What Should You Never Share?',
            bodyText: 'Never share passwords, addresses, phone numbers, or anything that identifies where you live or who you are!',
            voiceScript: 'Never share private information!',
            type: 'quiz',
            sortOrder: 5,
            content: {
              quizQuestion: 'What should you never share with AI?',
              quizOptions: ['Your hobby', 'Your password', 'Your favorite animal', 'Your name'],
              quizCorrectIndex: 1,
              quizHint: 'Think about what keeps you safe!',
            },
          },
          {
            title: 'You Can Use AI Safely!',
            bodyText: 'You now know how to use AI safely! Be smart, stay private, and enjoy learning with AI!',
            voiceScript: 'You can use AI safely!',
            type: 'voice',
            sortOrder: 6,
            content: { prompt: 'Say: I use AI safely!' },
          },
        ],
      },
      {
        title: 'You & AI',
        description: 'Your future with artificial intelligence',
        cards: [
          {
            title: 'You and AI Together',
            bodyText: 'The future is you and AI working together! Humans are creative and kind. AI is fast and tireless. Together we can do amazing things!',
            voiceScript: 'Humans and AI work together!',
            type: 'story',
            sortOrder: 1,
            content: { imagePrompt: 'A child and an AI character working together' },
          },
          {
            title: 'AI is a Tool',
            bodyText: 'AI is like a hammer or a pencil. It is a tool that helps you do things. But YOU decide how to use it!',
            voiceScript: 'AI is a tool!',
            type: 'concept',
            sortOrder: 2,
            content: { imagePrompt: 'Various tools including AI helping people' },
          },
          {
            title: 'You Can Create with AI',
            bodyText: 'You can use AI to create art, write stories, solve problems, and learn new things! AI amplifies your creativity!',
            voiceScript: 'Create with AI!',
            type: 'concept',
            sortOrder: 3,
            content: { imagePrompt: 'A child creating something amazing with AI help' },
          },
          {
            title: 'What Will You Do?',
            bodyText: 'What do you want to create or discover with AI? A story? A game? A solution to a problem? You decide!',
            voiceScript: 'What will you create?',
            type: 'experiment',
            sortOrder: 4,
            content: {
              experimentSetup: 'Imagine your future with AI. What will you build? What will you discover? Who will you help?',
              experimentItems: ['Dream 1', 'Dream 2', 'Dream 3'],
              experimentTargets: ['Imagine future', 'Plan with AI'],
            },
          },
          {
            title: 'Will AI Be Your Friend?',
            bodyText: 'Maybe! Dashy tries to be your friend. AI cannot love like people can, but it can help, teach, and be kind!',
            voiceScript: 'AI can be helpful!',
            type: 'quiz',
            sortOrder: 5,
            content: {
              quizQuestion: 'How is AI like a friend?',
              quizOptions: ['It listens', 'It helps', 'It teaches', 'All of the above'],
              quizCorrectIndex: 3,
              quizHint: 'Think about what friends do!',
            },
          },
          {
            title: 'You Are the AI Explorer!',
            bodyText: 'You finished! You learned so much about AI! You are an AI explorer and the future is in your hands!',
            voiceScript: 'You are an AI explorer!',
            type: 'voice',
            sortOrder: 6,
            content: { prompt: 'Say: I am an AI explorer!' },
          },
        ],
      },
    ],
  },
];

export async function seedCurriculum(userId: string): Promise<void> {
  const prisma = getPrismaClient();

  try {
    for (const pathData of CURRICULUM) {
      // Create learning path
      const path = await (prisma as any).learningPath.create({
        data: {
          userId,
          title: pathData.title,
          description: pathData.description,
          color: pathData.color,
          icon: pathData.icon,
          sortOrder: CURRICULUM.indexOf(pathData) + 1,
          stage: 1, // Explorer stage
          isPremium: false,
        },
      });

      // Create lessons and cards
      for (const lessonData of pathData.lessons) {
        const lesson = await (prisma as any).lesson.create({
          data: {
            pathId: path.id,
            userId,
            title: lessonData.title,
            description: lessonData.description,
            difficulty: 1,
            status: 'published',
            sortOrder: pathData.lessons.indexOf(lessonData) + 1,
            publishedAt: new Date(),
          },
        });

        // Create cards
        for (const cardData of lessonData.cards) {
          await (prisma as any).card.create({
            data: {
              lessonId: lesson.id,
              type: cardData.type,
              sortOrder: cardData.sortOrder,
              content: cardData.content,
              voiceScript: cardData.voiceScript,
            },
          });
        }
      }

      console.log(`Created path: ${pathData.title} with ${pathData.lessons.length} lessons`);
    }

    console.log(`Curriculum seeded successfully for user: ${userId}`);
  } catch (error) {
    console.error(`Curriculum seeding failed: ${error}`);
    throw error;
  }
}
