/**
 * OpenAI OAuth 2.0 implementation with PKCE (Proof Key for Code Exchange)
 *
 * Supports the OAuth 2.0 authorization code flow with PKCE for secure token exchange.
 * Reference: https://platform.openai.com/docs/plugins/authentication/oauth
 */

import { getConfig } from '@config';
import { randomBytes, createHash } from 'crypto';

export interface OAuthTokens {
  accessToken: string;
  refreshToken?: string;
  expiresIn: number;
  tokenType: string;
}

/**
 * Generates a PKCE code verifier
 * @returns A 128-character alphanumeric string
 */
export function generateCodeVerifier(): string {
  return randomBytes(96).toString('base64url');
}

/**
 * Generates a PKCE code challenge from a code verifier
 * @param codeVerifier - The code verifier generated by generateCodeVerifier()
 * @returns The base64url-encoded SHA-256 hash of the verifier
 */
export function generateCodeChallenge(codeVerifier: string): string {
  return createHash('sha256')
    .update(codeVerifier)
    .digest('base64url');
}

/**
 * Builds the OpenAI OAuth authorization URL
 * @param state - A random state string for CSRF protection
 * @param codeVerifier - The PKCE code verifier (to derive code_challenge)
 * @returns The full authorization URL to redirect the user to
 */
export function getAuthorizationUrl(state: string, codeVerifier: string): string {
  const config = getConfig();

  if (!config.OPENAI_OAUTH_CLIENT_ID) {
    throw new Error('OPENAI_OAUTH_CLIENT_ID not configured');
  }

  if (!config.OPENAI_OAUTH_REDIRECT_URI) {
    throw new Error('OPENAI_OAUTH_REDIRECT_URI not configured');
  }

  const codeChallenge = generateCodeChallenge(codeVerifier);

  const params = new URLSearchParams({
    client_id: config.OPENAI_OAUTH_CLIENT_ID,
    redirect_uri: config.OPENAI_OAUTH_REDIRECT_URI,
    response_type: 'code',
    scope: 'openid profile email',
    state,
    code_challenge: codeChallenge,
    code_challenge_method: 'S256',
  });

  return `https://auth.openai.com/authorize?${params.toString()}`;
}

/**
 * Exchanges an authorization code for OAuth tokens
 * @param code - The authorization code from the OAuth callback
 * @param codeVerifier - The PKCE code verifier (must match the one used to generate the challenge)
 * @returns The access and refresh tokens
 */
export async function exchangeCodeForTokens(
  code: string,
  codeVerifier: string
): Promise<OAuthTokens> {
  const config = getConfig();

  if (!config.OPENAI_OAUTH_CLIENT_ID) {
    throw new Error('OPENAI_OAUTH_CLIENT_ID not configured');
  }

  if (!config.OPENAI_OAUTH_CLIENT_SECRET) {
    throw new Error('OPENAI_OAUTH_CLIENT_SECRET not configured');
  }

  if (!config.OPENAI_OAUTH_REDIRECT_URI) {
    throw new Error('OPENAI_OAUTH_REDIRECT_URI not configured');
  }

  const payload = {
    grant_type: 'authorization_code',
    code,
    client_id: config.OPENAI_OAUTH_CLIENT_ID,
    client_secret: config.OPENAI_OAUTH_CLIENT_SECRET,
    redirect_uri: config.OPENAI_OAUTH_REDIRECT_URI,
    code_verifier: codeVerifier,
  };

  const response = await fetch('https://auth.openai.com/token', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(payload),
  });

  if (!response.ok) {
    const errorData = (await response.json()) as {
      error?: string;
      error_description?: string;
    };
    throw new Error(
      `OpenAI OAuth error: ${errorData.error} - ${errorData.error_description || ''}`
    );
  }

  const data = (await response.json()) as {
    access_token: string;
    refresh_token?: string;
    expires_in: number;
    token_type: string;
  };

  return {
    accessToken: data.access_token,
    refreshToken: data.refresh_token,
    expiresIn: data.expires_in,
    tokenType: data.token_type,
  };
}

/**
 * Refreshes an expired access token using the refresh token
 * @param refreshToken - The refresh token from a previous token exchange
 * @returns The new access and refresh tokens
 */
export async function refreshAccessToken(refreshToken: string): Promise<OAuthTokens> {
  const config = getConfig();

  if (!config.OPENAI_OAUTH_CLIENT_ID) {
    throw new Error('OPENAI_OAUTH_CLIENT_ID not configured');
  }

  if (!config.OPENAI_OAUTH_CLIENT_SECRET) {
    throw new Error('OPENAI_OAUTH_CLIENT_SECRET not configured');
  }

  const payload = {
    grant_type: 'refresh_token',
    refresh_token: refreshToken,
    client_id: config.OPENAI_OAUTH_CLIENT_ID,
    client_secret: config.OPENAI_OAUTH_CLIENT_SECRET,
  };

  const response = await fetch('https://auth.openai.com/token', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(payload),
  });

  if (!response.ok) {
    const errorData = (await response.json()) as {
      error?: string;
      error_description?: string;
    };
    throw new Error(
      `OpenAI token refresh error: ${errorData.error} - ${errorData.error_description || ''}`
    );
  }

  const data = (await response.json()) as {
    access_token: string;
    refresh_token?: string;
    expires_in: number;
    token_type: string;
  };

  return {
    accessToken: data.access_token,
    refreshToken: data.refresh_token,
    expiresIn: data.expires_in,
    tokenType: data.token_type,
  };
}

/**
 * Revokes a token at OpenAI
 * This invalidates both access and refresh tokens
 * @param token - The token to revoke (access or refresh)
 */
export async function revokeToken(token: string): Promise<void> {
  const config = getConfig();

  if (!config.OPENAI_OAUTH_CLIENT_ID) {
    throw new Error('OPENAI_OAUTH_CLIENT_ID not configured');
  }

  if (!config.OPENAI_OAUTH_CLIENT_SECRET) {
    throw new Error('OPENAI_OAUTH_CLIENT_SECRET not configured');
  }

  const payload = {
    token,
    client_id: config.OPENAI_OAUTH_CLIENT_ID,
    client_secret: config.OPENAI_OAUTH_CLIENT_SECRET,
  };

  const response = await fetch('https://auth.openai.com/revoke', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(payload),
  });

  if (!response.ok) {
    const errorData = (await response.json()) as {
      error?: string;
      error_description?: string;
    };
    throw new Error(
      `OpenAI token revocation error: ${errorData.error} - ${errorData.error_description || ''}`
    );
  }
}
